---
# tasks file for ansible-role-localhost-management
  - name: "local /etc/hosts - flush hosts"
    lineinfile:
      dest: "/etc/hosts"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
      state: absent
    delegate_to: 127.0.0.1
    
  - name: "local /etc/hosts - update hosts"
    lineinfile:
      dest: "/etc/hosts"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
      state: present
    delegate_to: 127.0.0.1
    
  ### SSH Config
  - name: "{{ lookup('env', 'HOME') }}/.ssh/config"
    blockinfile:
      dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
      content: |
        Host {{ ansible_fqdn }}
          StrictHostKeyChecking yes
          port {{ ansible_ssh_port }}
          User {{ ansible_ssh_user }}
          Hostname {{ ansible_default_ipv4.address }}
      state: present
    delegate_to: 127.0.0.1 

  ### Ansible inventory
  - name: Create evil-inventory file
    ansible.builtin.file:
      state: touch
      path: "{{ playbook_dir }}/../eviltory"
      mode: 0755
      owner: "{{ lookup('env', 'USER')}}"
    delegate_to: 127.0.0.1 
    run_once: yes

  - name: Create unique group list
    set_fact:
      hostgroups: "{{ groups['invited'] | map('extract', hostvars, 'classify_facts') | map(attribute='classification') | replace('.','_') | list | unique }}"
    run_once: yes
    delegate_to: 127.0.0.1

  - name: "## `evil-block` start"
    lineinfile:
      dest: "{{ playbook_dir }}/evil-inventory"
      line: "## `evil-block` start"
      state: present
    delegate_to: 127.0.0.1 
    run_once: yes

  - name: "Build `evil-inventory` group:vars block"
    lineinfile:
      dest: "{{ playbook_dir }}/evil-inventory"
      line: "[{{ item }}:vars]"
      state: present
    delegate_to: 127.0.0.1 
    run_once: yes
    loop: "{{ hostgroups }}"

  - name: "Build `evil-inventory` group block"
    lineinfile:
      dest: "{{ playbook_dir }}/evil-inventory"
      line: "[{{ item }}]"
      insertbefore: "[{{ item }}:vars]"
      state: present
    delegate_to: 127.0.0.1 
    run_once: yes
    loop: "{{ hostgroups }}"

  - name: "## `evil-block` end"
    lineinfile:
      dest: "{{ playbook_dir }}/evil-inventory"
      line: "## `evil-block` end"
      insertbefore: "[{{ item }}:vars]"
      state: present
    delegate_to: 127.0.0.1 
    run_once: yes
    

  # - name: "Enrich local inventory file"
  #   lineinfile:
  #     dest: "../inventory"
  #     line: "{{ ansible_hostname }}.{{ ansible_dns.search[0] }} type={{ classification }}"
  #     # insertafter: "[{{ ansible_dns.search[0] | replace('-','_') | replace('.','_') }}]"
  #     insertbefore: "[enrolled:vars]"
  #     state: present
  #   delegate_to: 127.0.0.1 

  # - name: "Update invited group in local inventory file"
  #   lineinfile:
  #     dest: "../inventory"
  #     regex: "^{{ ansible_default_ipv4.address }}*"
  #     line: "{{ ansible_default_ipv4.address }} group={{ ansible_dns.search[0] | replace('-','_') | replace('.','_') }} type={{ classification }}"
  #     insertbefore: "[{{ ansible_dns.search[0] | replace('-','_') | replace('.','_') }}:vars]"
  #     insertafter: "[invited]"
  #   delegate_to: 127.0.0.1 